### ISSUE TITLE
Problematic warning with "Middleware" integration

### ISSUE THREAD

**Issue by sgalinski** [lochmueller/staticfilecache#150]
I get the following warning if the e.g. 404 page needs to be delivered.

(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Illegal string offset 'cache_timeout' in /var/www/website-base.dev/web/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php line 4583

![image](https://user-images.githubusercontent.com/122370/57320239-b60fbe80-70fe-11e9-9513-a94d6eec8620.png)

**Comment by lochmueller** [comment]
Hey @sgalinski 
Hmm... that is strange.  Seems to be a core bug or a to high error (notice!) logging.
Can handle/check the variable because it is TSFE internal.
Regards,
Tim

**Comment by lochmueller** [comment]
Ohh... perhaps the middleware is "to early" in the middleware stack?!

**Comment by sgalinski** [comment]
We found already several internal issues with the middleware stuff in our custom extensions that we already ported. Also with caching and language handling. It's really difficult to debug and handle this issues properly. I guess to fix the warning is only the half truth as it seems like something is missing in general here. Maybe it's simply really to early in the process.
I switched back to your default hook now. Unfortunately no time to dig much deeper here. Thanks for all your work on this nice extension btw. One of the very few external TYPO3 extensions we use at all in our projects. :-)

**Comment by lochmueller** [comment]
Thanks for the Feedback. I will check this in my test envs in the next days.

**Comment by lochmueller** [comment]
Hey @sgalinski ,

I checked tthis again and do not get the error :-/ I think the position is good, becase the StaticFileCache Middleware call the handler of the next first and then try to cache the content. So the complete TSFE should be done/finished.

Could you check in your case why $this->page is empty in the core and when it get filled?

Regards,
Tim

![Bildschirmfoto 2019-05-10 um 14 02 08](https://user-images.githubusercontent.com/3907126/57525886-38c99100-732c-11e9-994d-50eb5914cdb5.png)

**Comment by sgalinski** [comment]
Please find attached a mini patch for this issue. I really don't have any idea why this happens, but the page array is completely array in this situations. 

[FixCrashIfPageIsEmptyInMiddlewareHookThatCanHappenIn404Cases.txt](https://github.com/lochmueller/staticfilecache/files/3183337/FixCrashIfPageIsEmptyInMiddlewareHookThatCanHappenIn404Cases.txt)

**Comment by lochmueller** [comment]
Fixed the problem in the current master. Will add some logging shortly...

**Comment by sgalinski** [comment]
@lochmueller Unfortunately the bug is still there. New version of the patch attached.

[FixCrashIfPageIsEmptyInMiddlewareHookThatCanHappenIn404Cases.txt](https://github.com/lochmueller/staticfilecache/files/3275446/FixCrashIfPageIsEmptyInMiddlewareHookThatCanHappenIn404Cases.txt)

**Comment by lochmueller** [comment]
Hey @sgalinski 
I fixed this by adding a new cache rule: https://github.com/lochmueller/staticfilecache/commit/b240fc778dc47af0f89c2fbff5f6333fdd253907
Regards,
Tim

**Comment by sgalinski** [comment]
@lochmueller Nice. Thanks!
