### ISSUE TITLE
Boostmode never regenerates Cache

### ISSUE THREAD

**Issue by MartinH0** [lochmueller/staticfilecache#187]
## Bug Report

**Current Behavior**
I activated Boostmode and the Timestamp to track the Files.

1. Clear all Caches (manually in the Server as you are in Boostmode)
2. Call the Frontend so the Cache gets generated again
3. Verify the Cache is fresh (see Timestamp)
4. Edit a tiny thing in the Backend on the site (Text change etc)
5. Run the Crons manually to speed things up
6. Check frontend if changes are now visible
7. Check if the Timestamp of the Cache changed

For me the change I mande was not visible in the frontend and the Cach did not get cleared or even regenerated.

Means as soon as you activate the Boostmode your Site will never change, no matter what you do.

Also strange: 

1. Timestamp says: `<!-- expires on: 01-01-70 01:00 -->`
2. Generated htaccess does say: `ExpiresByType text/html M-1570080334` while my Cachetime (cache_period) was set to 3600

**Environment**
- TYPO3 version(s): 9.5.9
- staticfilecache version: 10.0.0

**Possible Solution**
I think the problem is that the Cache in Bootstmode is valid "unlimited" (like the Timestamp shows) and so the system thinks it does not have to regenerate them.

But in fact it should be like this:

The Cache should be valide as long the cache_period tells it have to and after this it should be added to the queue to be regenerated and to replace the old cache.

**Comment by lochmueller** [comment]
Hmm... could you send me the comit of your 10.0.0-dev version? I think I fixed this already:
https://github.com/lochmueller/staticfilecache/commit/5466e58c8d3209a187595e16d4ff2268bf0718c5

Thanks for testing the upcomming release 👍 Please update to the current commit "bda522f8207b9fa226948d36532928a6dbbeab3e".

Regards,
Tim

**Comment by MartinH0** [comment]
The comit of the Version was "18140188dee9b9d6e5b086a202e1be7011007e40"
I will update to the latest Version an retest the whole thing at TYPO3 v10.1

Thanks for keeping that Extension supported!

**Comment by MartinH0** [comment]
Actually this did not fix the Problem.

I will explain what I did. Please correct me if I did something wrong:

1. Clear all Caches (manually in the Server as you are in Boostmode)
2. Call the Frontend so the Cache gets generated again
3. Verify the Cache is fresh (see Timestamp when the File gets generated)
4. Edit a tiny thing in the Backend on the site (Text change etc)
5. Run the Crons manually to speed things up (did this 3 Times!)
6. Check frontend if changes are now visible
7. Check if the Timestamp of the Cache changed

Here my Crons:


I think there are 2 problems:

1. the command `staticfilecache:flushCache` does not flush the Cache in Boost-Mode (does not push it in the queue)
2. Things should **not** be Time-Driven but more **Event-Driven**

Let me explain the second point:

After you have a valid Cache of every Page, nothing will ever change the website untill someone changes something!
This Cache could last forever and nothing would be wrong. (we asume there is no dynamic content which needs to be cleared every x min)

Then I reallised that the regeneration of the Cache is just needed, if someone changes the content of something (and saves!!) after saving TYPO3 also manages to recreate the Cache, so there have to be a hook which is event driven.

Now imagine this with Boosted Cache:
If you never change a Page it seriously will never be regenerated (which is good) and if you make a change to a page it immediately gets regenerated, you dont have to wait for the cron to purge the cache and the other Cron to regenerate it.

I think anyway that Timebased Clearing of the Cache is important (at variables like copyright "years" etc) as they should be regenerated sometimes but it does not have to be often (max once a day!) and all the other changes are Event-Driven.

With Event-Driven Cache-Regeneration the cache will be much faster up to date and changes will be faster visible to the Visitor

.

Just my 2cents

**Comment by lochmueller** [comment]
Hey @MartinH0 
thanks for the details. I will check this.
Just for note: The cache is already "event driven". You do not need the "flushCache" command. TYPO3 call flushByTag-calls on the cachingframework if the editor run changes. Since the StaticFileCache is a real CachingFramework Frontend/Backend the flushByTag (with pageId_XXX) are detected by StaticFileCache and the right pages are added to the Queue.
But i will check if there is a problem in the Mechanim BoostRefresh.
Regards,
Tim

**Comment by MartinH0** [comment]
@lochmueller hi again,
thanks for clearing that out, just did not knew this as its not working right now to clear the Cache but will re-test it as soon as you say it is working. Would be awesome if it works eventdriven.

FYI: I'm on TYPO3 10 right now if this makes a difference

**Comment by lochmueller** [comment]
1.) Delete cache and all StaticFileCache Tables (cache, Tags, Queue)
2.) Call a frontend page -> Result: Files should be created and a entry in backend view should be visible. Queue should be empty.
3.) Change a content on the page (You describe this as event driven) -> Result: There should be a entry in the Queue, but no new Cache. (Not also a clear cache in BE or using the flushCache command should only fill up the Queue and do not delete the files)
4.) Run "staticfilecache:boostQueueRun" -> Result: The Queue entries have a call_date and a call_result. The files should be new.

The problem was in the last part. The GenerateMiddleware do not recreate the entry, because the files are already exists. I solv this issue with the last commit.
